server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: tache-service-route
          uri: lb://xprojetservice  # Utiliser tout en minuscule
          predicates:
            - Path=/p/projet/**
    discovery:
      locator:
        enabled: true  # Enables service discovery for routing
        lower-case-service-id: true  # Ensures the service id is in lowercase for consistency


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
