server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?allowPublicKeyRetrieval=true&useSSL=false

    username: root
    password: 1234ham
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

