spring:
  application:
    name: xprojetService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projets
    hikari:
      username: root
      password: ADMIN
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: db/migration
    baseline-on-migrate: true
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 9090

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  config:
    taches-url: http://localhost:8090/api/v2/taches
